In [ ]:
!pip install --upgrade torch==1.7.1 torchtext==0.8.1 torchvision==0.8.2

     |████████████████████████████████| 776.8MB 17kB/s 
     |████████████████████████████████| 7.0MB 38.5MB/s 
     |████████████████████████████████| 12.8MB 34.7MB/s 
  Found existing installation: torch 1.8.1+cu101
    Uninstalling torch-1.8.1+cu101:
      Successfully uninstalled torch-1.8.1+cu101
  Found existing installation: torchtext 0.9.1
    Uninstalling torchtext-0.9.1:
      Successfully uninstalled torchtext-0.9.1
  Found existing installation: torchvision 0.9.1+cu101
    Uninstalling torchvision-0.9.1+cu101:
      Successfully uninstalled torchvision-0.9.1+cu101


In [ ]:
!pip install -U pip setuptools wheel
!pip install -U spacy
!python -m spacy download en_core_web_sm

     |████████████████████████████████| 1.5MB 6.3MB/s 
Requirement already up-to-date: setuptools in /usr/local/lib/python3.7/dist-packages (54.2.0)
Requirement already up-to-date: wheel in /usr/local/lib/python3.7/dist-packages (0.36.2)
  Found existing installation: pip 19.3.1
    Uninstalling pip-19.3.1:
      Successfully uninstalled pip-19.3.1
     |████████████████████████████████| 12.8 MB 328 kB/s 
     |████████████████████████████████| 456 kB 53.2 MB/s 
     |████████████████████████████████| 9.1 MB 50.8 MB/s 
     |████████████████████████████████| 1.1 MB 60.7 MB/s 
     |████████████████████████████████| 113 kB 46.1 MB/s 
  Created wheel for smart-open: filename=smart_open-3.0.0-py3-none-any.whl size=107097 sha256=492095f62e3f927cd2d75f15d805f25e76c959410cc140cebcd86604c1500f69
  Stored in directory: /root/.cache/pip/wheels/83/a6/12/bf3c1a667bde4251be5b7a3368b2d604c9af2105b5c1cb1870
Successfully built smart-open
  Attempting uninstall: catalogue
    Found existing installati

In [15]:
import torch, torchtext, numpy as np
import pandas as pd, csv
from torch import nn, optim
from tqdm.auto import tqdm
import matplotlib.pyplot as plt
#import pdbf

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving text_dataset.csv to text_dataset.csv


In [40]:
#dataset_full = pd.read_csv('text_dataset.csv')

In [ ]:
#dataset_full

In [17]:
data_train_csv = pd.read_csv('train.txt', sep=';', names = ['caption', 'sentiment'])
data_train_csv.to_csv('train.csv')

In [18]:
data_train_csv

caption sentiment
0                                i didnt feel humiliated   sadness
1      i can go from feeling so hopeless to so damned...   sadness
2       im grabbing a minute to post i feel greedy wrong     anger
3      i am ever feeling nostalgic about the fireplac...      love
4                                   i am feeling grouchy     anger
...                                                  ...       ...
15995  i just had a very brief time in the beanbag an...   sadness
15996  i am now turning and i feel pathetic that i am...   sadness
15997                     i feel strong and good overall       joy
15998  i feel like this was such a rude comment and i...     anger
15999  i know a lot but i feel so stupid because i ca...   sadness

[16000 rows x 2 columns]

In [19]:
data_test_csv = pd.read_csv('test.txt', sep=';', names = ['caption', 'sentiment'])
data_test_csv.to_csv('test.csv')

In [20]:
data_test_csv

caption sentiment
0     im feeling rather rotten so im not very ambiti...   sadness
1             im updating my blog because i feel shitty   sadness
2     i never make her separate from me because i do...   sadness
3     i left with my bouquet of red and yellow tulip...       joy
4       i was feeling a little vain when i did this one   sadness
...                                                 ...       ...
1995  i just keep feeling like someone is being unki...     anger
1996  im feeling a little cranky negative after this...     anger
1997  i feel that i am useful to my people and that ...       joy
1998  im feeling more comfortable with derby i feel ...       joy
1999  i feel all weird when i have to meet w people ...      fear

[2000 rows x 2 columns]

In [21]:
data_validation_csv = pd.read_csv('val.txt', sep=';', names = ['caption', 'sentiment'])
data_validation_csv.to_csv('val.csv')

In [22]:
data_validation_csv

caption sentiment
0     im feeling quite sad and sorry for myself but ...   sadness
1     i feel like i am still looking at a blank canv...   sadness
2                        i feel like a faithful servant      love
3                     i am just feeling cranky and blue     anger
4     i can have for a treat or if i am feeling festive       joy
...                                                 ...       ...
1995  im having ssa examination tomorrow in the morn...   sadness
1996  i constantly worry about their fight against n...       joy
1997  i feel its important to share this info for th...       joy
1998  i truly feel that if you are passionate enough...       joy
1999  i feel like i just wanna buy any cute make up ...       joy

[2000 rows x 2 columns]

In [23]:
complete_dataset_csv = data_train_csv
complete_dataset_csv = complete_dataset_csv.append(data_test_csv)
complete_dataset_csv = complete_dataset_csv.append(data_validation_csv)
complete_dataset_csv.to_csv('complete_dataset.csv')
complete_dataset_csv

caption sentiment
0                               i didnt feel humiliated   sadness
1     i can go from feeling so hopeless to so damned...   sadness
2      im grabbing a minute to post i feel greedy wrong     anger
3     i am ever feeling nostalgic about the fireplac...      love
4                                  i am feeling grouchy     anger
...                                                 ...       ...
1995  im having ssa examination tomorrow in the morn...   sadness
1996  i constantly worry about their fight against n...       joy
1997  i feel its important to share this info for th...       joy
1998  i truly feel that if you are passionate enough...       joy
1999  i feel like i just wanna buy any cute make up ...       joy

[20000 rows x 2 columns]

In [24]:
complete_dataset_csv.sentiment.unique()

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [31]:
complete_dataset_csv['sentiment'] = complete_dataset_csv['sentiment'].replace(['sadness','joy','anger','love','fear'],['2','1','0','3','2'])

In [32]:
complete_dataset_csv

caption sentiment
0                               i didnt feel humiliated         2
1     i can go from feeling so hopeless to so damned...         2
2      im grabbing a minute to post i feel greedy wrong         0
3     i am ever feeling nostalgic about the fireplac...         3
4                                  i am feeling grouchy         0
...                                                 ...       ...
1995  im having ssa examination tomorrow in the morn...         2
1996  i constantly worry about their fight against n...         1
1997  i feel its important to share this info for th...         1
1998  i truly feel that if you are passionate enough...         1
1999  i feel like i just wanna buy any cute make up ...         1

[20000 rows x 2 columns]

In [35]:
complete_dataset_csv = complete_dataset_csv[complete_dataset_csv.sentiment != 'surprise']

In [37]:
complete_dataset_csv.sentiment.unique()

array(['2', '0', '3', '1'], dtype=object)

In [39]:
complete_dataset_csv

caption sentiment
0                               i didnt feel humiliated         2
1     i can go from feeling so hopeless to so damned...         2
2      im grabbing a minute to post i feel greedy wrong         0
3     i am ever feeling nostalgic about the fireplac...         3
4                                  i am feeling grouchy         0
...                                                 ...       ...
1995  im having ssa examination tomorrow in the morn...         2
1996  i constantly worry about their fight against n...         1
1997  i feel its important to share this info for th...         1
1998  i truly feel that if you are passionate enough...         1
1999  i feel like i just wanna buy any cute make up ...         1

[19281 rows x 2 columns]

In [46]:
complete_dataset_csv.to_csv('complete_dataset_final.csv')

sentiments: 0 for angry; 1 for happy; 2 for sad; 3 for sleepy

In [48]:
class dataset_cat_sentiments(torch.utils.data.Dataset):

  def __init__(self, csv_data, vocab=None):
    self.csv_dataset = pd.read_csv(csv_data)
    self.tokenizer = torchtext.data.utils.get_tokenizer('spacy', 'en_core_web_sm')
    toks = self.tokenizer(" ".join(self.csv_dataset.caption.unique()))

    if vocab is None:
            self.vocab = torchtext.vocab.build_vocab_from_iterator([toks])
    else:
            self.vocab = vocab
    self.toks = torch.LongTensor([self.vocab[tok] for tok in toks])
    self.LABELS = self.csv_dataset.sentiment.unique()
    self.LENGTH = self.csv_dataset.shape[0]
    self.label_dict = dict(zip(self.LABELS,range(len(self.LABELS))))

    self.dataset_dict = []
    for i in range(self.LENGTH):
      labels_ret = self.label_dict[self.csv_dataset.iloc[i].sentiment]
      toks = self.tokenizer(self.csv_dataset.iloc[i].caption)
      toks_ret = torch.LongTensor([self.vocab[tok] for tok in toks])
      self.dataset_dict.append((labels_ret, toks_ret))
    
    
  def get_labels(self):
    return set([(i) for i in range(len(self.LABELS))])

  def get_vocab(self):
    return self.vocab

  def DATASETS(self):
    return self.dataset_dict[:int(self.LENGTH*8/10)], self.dataset_dict[int((self.LENGTH*(8/10))+1):]

  def __len__(self):
    return self.LENGTH

  def __getitem__(self, i):
    
    # labels_ret = self.label_dict[self.csv_dataset.iloc[i].sentiment]
    # toks = self.tokenizer(self.csv_dataset.iloc[i].text)
    # toks_ret = torch.LongTensor([self.vocab[tok] for tok in toks])
    # return (labels_ret, toks_ret)
    return self.dataset_dict[i]

In [49]:
ap = dataset_cat_sentiments('complete_dataset_final.csv')
ap.LABELS
ap.get_labels()
ap

1lines [00:00, 15.74lines/s]


In [51]:
train_ds, test_ds = ap.DATASETS()

In [56]:
vb = ap.get_vocab()
len(vb)
vb.itos[:10]

['<unk>', '<pad>', 'i', 'feel', 'and', 'to', 'the', 'a', 'feeling', 'that']

In [53]:
vb.stoi['should']

115

In [54]:
xs, ys = ap[0]
' '.join([ap.vocab.itos[x] for x in ys])

'i did nt feel humiliated'

In [57]:
def mk_offsets(samples):
    txts = [txt for _, txt in samples]
    lens = [0] + [len(txt) for txt in txts]
    offs = torch.tensor(lens[:-1]).cumsum(0)
    labs = torch.tensor([lab for lab, txt in samples])
    txts = torch.cat(txts)
    return labs, txts, offs

In [58]:
mk_offsets(test_ds[0:4])

(tensor([3, 1, 0, 0]),
 tensor([   2,    3,  326,    4,  104, 1359,    2,    3,   14,   23,   18,  184,
            7,  521, 1036,    4,    2,   15,  337,    9,   43,    2,   47,    7,
          157,   21,    2,    3,   16,  289,   39,    2,   41,   26, 4365,   13,
            2,   15,    8,  205,  693,   16,    2,   15,   26,   46, 4646,  109,
           64]),
 tensor([ 0,  6, 21, 36]))

In [59]:
class TextCats(nn.Module):
    def __init__(self, n_words, emb_dim, n_cats):
        super().__init__()
        self.embedding = nn.EmbeddingBag(n_words, emb_dim, mode='mean', sparse=True)
        self.fc = nn.Linear(emb_dim, n_cats)
        nn.init.xavier_uniform_(self.embedding.weight.data)
        nn.init.xavier_uniform_(self.fc.weight.data)
    def forward(self, text, offs):
        emb = self.embedding(text, offs)
        return self.fc(emb)

In [60]:
device = torch.device('cpu')

def run_test(model, ds, crit):
    model.eval()
    total_loss, total_acc = 0, 0
    ldr = torch.utils.data.DataLoader(ds, batch_size=16, collate_fn=mk_offsets)
    for labs, txts, offs in tqdm(ldr, leave=False, desc='test iter'):
        labs, txts, offs = labs.to(device), txts.to(device), offs.to(device)
        with torch.no_grad():
            outs = model(txts, offs)
            loss = crit(outs, labs)
            total_loss += loss.item()
            total_acc += (outs.argmax(1) == labs).sum().item()
    return total_loss / len(ds), total_acc / len(ds)

def run_train(model, ds, crit, opt, sched):
    model.train()
    total_loss, total_acc = 0, 0
    ldr = torch.utils.data.DataLoader(ds, batch_size=16, collate_fn=mk_offsets, shuffle=True)
    for labs, txts, offs in tqdm(ldr, leave=False, desc='train iter'):
        opt.zero_grad()
        labs, txts, offs = labs.to(device), txts.to(device), offs.to(device)
        outs = model(txts, offs)
        loss = crit(outs, labs)
        loss.backward()
        opt.step()
        total_loss += loss.item()
        total_acc += (outs.argmax(1) == labs).sum().item()
    sched.step()
    return total_loss / len(ds), total_acc / len(ds)

def run_all(model, test_ds, train_ds, crit, opt, sched, n_epochs=10):
    for epoch in tqdm(range(n_epochs), desc='epochs'):
        train_loss, train_acc = run_train(model, train_ds, crit, opt, sched)
        test_loss, test_acc = run_test(model, test_ds, crit)
        tqdm.write(f'epoch {epoch}   train loss {train_loss:.6f} acc {train_acc:.4f}   test loss {test_loss:.6f} acc {test_acc:.4f}') 

In [64]:
model = TextCats(len(vb), 50, 4)
model.to(device);

In [65]:
crit = nn.CrossEntropyLoss().to(device)
opt = optim.SGD(model.parameters(), lr=3.0)
sched = optim.lr_scheduler.StepLR(opt, 1, gamma=0.7)

In [66]:
run_all(model, test_ds, train_ds, crit, opt, sched, 10) 

epoch 0   train loss 0.068137 acc 0.5282   test loss 0.119199 acc 0.4357


epoch 1   train loss 0.030073 acc 0.8233   test loss 0.023778 acc 0.8517


epoch 2   train loss 0.016282 acc 0.9131   test loss 0.018990 acc 0.8952


epoch 3   train loss 0.011931 acc 0.9397   test loss 0.017030 acc 0.9015


epoch 4   train loss 0.009123 acc 0.9601   test loss 0.016154 acc 0.9077


epoch 5   train loss 0.007738 acc 0.9681   test loss 0.015633 acc 0.9110


epoch 6   train loss 0.006870 acc 0.9735   test loss 0.015753 acc 0.9064


epoch 7   train loss 0.006334 acc 0.9762   test loss 0.015385 acc 0.9123


epoch 8   train loss 0.005982 acc 0.9794   test loss 0.015197 acc 0.9147


epoch 9   train loss 0.005710 acc 0.9809   test loss 0.015266 acc 0.9149

